name: Submodules

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
  push:
    branches:
      - main

jobs:
  submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: bioexcel/biobb_community_wfs
          path: ./

      - name: Update submodules
        run: git submodule update --remote

      - name: Commit and Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add . && git commit -m "Updated submodules" && git push
          else
            echo "No changes to commit"
          fi